
```{r setup-0, include = FALSE}
knitr::opts_chunk$set(
  collapse = TRUE, comment = "#>", message = FALSE, warning = FALSE,
  echo = FALSE, fig.path = "figures/"
)

# Packages --------------------------------------------------------------
library(dissmapr)   # pkgdown has already installed the package
library(httr)
library(geodata)
library(data.table)
library(dplyr)
library(tidyr)
library(zoo)
library(sf)
library(terra)
library(tidyterra)
library(zetadiv)
library(ggplot2)
library(viridis)
library(patchwork)
library(mclust)
library(zen4R)
library(purrr)
library(RColorBrewer)
```

```{r cache, include = FALSE}
## load every object saved in inst/extdata/dissmapr_cache.RData
load(
  system.file("extdata", "dissmapr_cache.RData",
              package = "dissmapr"),
  envir = knitr::knit_global()   # make them visible to the vignette
)

## load all cached objects created by usethis::use_data()
# data("dissmapr_cache", package = "dissmapr", envir = environment())

# # Read rasters separately
# grid_masked <- terra::rast(
#   system.file("extdata", "grid_masked.tif", package = "dissmapr")
# )
# effRich_r     <- terra::rast(
#   system.file("extdata", "effRich_r.tif", package = "dissmapr")
# )
# env_r <- terra::rast(
#   system.file("extdata", "env_r.tif", package = "dissmapr")
# )
# env_effRich_r     <- terra::rast(
#   system.file("extdata", "env_effRich_r.tif", package = "dissmapr")
# )
# future_r <- terra::rast(
#   system.file("extdata", "future_r.tif", package = "dissmapr")
# )
# result_bioregDiff     <- terra::rast(
#   system.file("extdata", "result_bioregDiff", package = "dissmapr")
# )
# future_bioregDiff <- terra::rast(
#   system.file("extdata", "future_bioregDiff.tif", package = "dissmapr")
# )


```
