# .github/workflows/R-CMD-check.yaml

name: R-CMD-check

on:
  push:
    branches: [ main, master ]
  pull_request:

permissions:
  contents: read

jobs:
  R-CMD-check:
    runs-on: ubuntu-latest
    env:
      GITHUB_PAT: ${{ secrets.GITHUB_TOKEN }}
      R_KEEP_PKG_SOURCE: yes

    steps:
      # 1. Get your code
      - uses: actions/checkout@v4

      # 2. Install R
      - uses: r-lib/actions/setup-r@v2
        with:
          use-public-rspm: true

      # 4. Run build & check using the restored environment
      - uses: r-lib/actions/check-r-package@v2
        with:
          # leave out `use_renv: false` so it *does* use renv
          use_renv: false
          upload-snapshots: true
          build_args: 'c("--no-manual","--compact-vignettes=gs+qpdf")'
