# .github/workflows/R-CMD-check.yaml

name: R-CMD-check

on:
  push:
    branches: [main, master]
  pull_request:

permissions:
  contents: read

jobs:
  R-CMD-check:
    runs-on: ubuntu-latest

    env:
      GITHUB_PAT: ${{ secrets.GITHUB_TOKEN }}
      R_KEEP_PKG_SOURCE: yes       # keep sources for reproducibility

    steps:
      # 1 ── Get the code ---------------------------------------------------
      - uses: actions/checkout@v4

      # 2 ── Install R and system libs -------------------------------------
      - uses: r-lib/actions/setup-r@v2
        with:
          use-public-rspm: true      # binary packages → faster CI

      # 3 ── Restore the renv library (+ cache) ----------------------------
      - uses: r-lib/actions/setup-renv@v2   # replaces the old `use_renv:` input

      # 4 ── Run R CMD check -----------------------------------------------
      - uses: r-lib/actions/check-r-package@v2
        with:
          build_args: '--no-manual --compact-vignettes=gs+qpdf'
          upload-snapshots: true      # upload {testthat} Snapshots
