# .github/workflows/R-CMD-check.yaml
# -------------------------------------------------------------------------

name: R-CMD-check

on:
  push:
    branches: [main, master]
  pull_request:

permissions:
  contents: read

jobs:
  R-CMD-check:
    runs-on: ubuntu-latest

    env:
      GITHUB_PAT: ${{ secrets.GITHUB_TOKEN }}
      R_KEEP_PKG_SOURCE: yes

    steps:
      # 1 ── Get the code ---------------------------------------------------
      - uses: actions/checkout@v4

      # 2 ── Install R -------------------------------------------------------
      - uses: r-lib/actions/setup-r@v2
        with:
          use-public-rspm: true

      # 3 ── Install system + spatial + PDF tools ---------------------------
      - name: Install system requirements
        run: |
          sudo apt-get update -y
          sudo apt-get install -y \
            libproj-dev proj-data proj-bin \
            libgdal-dev gdal-bin \
            libgeos-dev \
            libudunits2-dev \
            ghostscript \
            qpdf
          # sanity-checks
          which qpdf || { echo 'qpdf not found'; exit 1; }
          which gs   || { echo 'gs not found';  exit 1; }

      # 4 ── Install Pandoc (needed for R-markdown vignettes) ---------------
      - uses: r-lib/actions/setup-pandoc@v2   # puts 'pandoc' on $PATH

      # 5 ── Restore and cache the renv library -----------------------------
      - uses: r-lib/actions/setup-renv@v2

      # 6 ── Run R CMD check -------------------------------------------------
      - uses: r-lib/actions/check-r-package@v2
        with:
          build_args: 'c("--no-manual", "--compact-vignettes=gs+qpdf")'
          upload-snapshots: true
